# Generated by Django 4.2.3 on 2023-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_alter_article_options_tag_scope_article_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag', verbose_name='Теги'),
        ),
    ]
