# Generated by Django 4.2.3 on 2023-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default='1990-01-01', verbose_name='Дата публикации'),
        ),
    ]
