# Generated by Django 4.2.3 on 2023-08-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_lte_exists_alter_phone_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default='2010-01-01', verbose_name='Дата выпуска'),
        ),
    ]
